# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20190815_0201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='mybook',
        ),
    ]
