# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30)),
                ('price', models.DecimalField(db_column='jiage', decimal_places=2, max_digits=7, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pub', models.CharField(max_length=30)),
            ],
        ),
    ]
