# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-30 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
