# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190830_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='博客创建时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='博客修改时间'),
        ),
    ]
