# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default='99999', max_digits=7, verbose_name='零售价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default='99999', max_digits=7, verbose_name='定价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.CharField(max_length=30, null=True, verbose_name='出版社'),
        ),
    ]
