# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-15 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='作者姓名')),
                ('age', models.IntegerField(default=1, verbose_name='作者年龄')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='作者邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='零售价格')),
                ('pub', models.CharField(max_length=30, verbose_name='出版社')),
            ],
        ),
    ]
