# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0003_auto_20190902_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='留言内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='留言创建时间')),
                ('parent_message', models.IntegerField(default=0)),
                ('publisher_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='留言的发布者')),
                ('topic_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='topic.Topic', verbose_name='文章')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
